name: 本番デプロイ

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: リリース通知
  SLACK_ICON: (画像ファイルパス)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Slack Notification on start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: release start
          SLACK_MESSAGE: リリースを開始します
          SLACK_COLOR: good
      
      - name: generate tag
        run: |
           echo "tag-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
           git tag $(cat TAG_NAME)
           git push origin $(cat TAG_NAME)
           
      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: release start
          SLACK_MESSAGE: タグ作成完了&リリース開始
          SLACK_COLOR: good
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: test and build and deploy
        id: main_step
        run: |
           cd /home/runner/work/githubactions_lambda/githubactions_lambda/githubaction_deploy/hello-world
           npm init -y
           npm install chai
           npm install mocha
           npm run test /home/runner/work/githubactions_lambda/githubactions_lambda/githubaction_deploy/hello-world/tests/unit/test-handler.js
           sam build -t /home/runner/work/githubactions_lambda/githubactions_lambda/githubaction_deploy/template.yaml
           sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file /home/runner/work/githubactions_lambda/githubactions_lambda/githubaction_deploy/samconfig.toml
      
      - if: steps.main_step.outcome =='success'
        name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: release start
          SLACK_MESSAGE: リリース終了
          SLACK_COLOR: good
          
      - if: failure() && steps.main_step.outcome !='failure'
        name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: release start
          SLACK_MESSAGE: テスト前エラー
          SLACK_COLOR: error
      
      - if: failure() && steps.main_step.outcome =='failure'
        name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: release start
          SLACK_MESSAGE: リリース失敗
          SLACK_COLOR: error
